[workspace]
members = ["core", "compiler", "decompiler", "cli", "scc"]

[workspace.package]
version = "0.5.11"
authors = ["jekky"]
edition = "2021"

[workspace.dependencies]
log = "0.4"
thiserror = "1"
itertools = "0.10"
strum = { version = "0.24", features = ["derive"] }
enum-as-inner = "0.5"
byteorder = "1.4"
flexstr = "0.9"
flexi_logger = { version = "0.24", default-features = false }

[workspace.metadata.release]
shared-version = true
consolidate-commits = true
publish = false
tag-prefix = ""

[profile.release]
lto = "thin"
