[package]
name = "scc-ctests"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dev-dependencies]
minidl = "0.1"
pretty_assertions = "1"
assert_fs = "1"
offset = "0.1"

[build-dependencies]
bindgen = "0.69"
